### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by hojongs** [leejaycoke/pilot-react#1]
안녕하세요, 개발바닥 유투브 커뮤니티 보고 왔습니다 ㅋㅋ

호출이 localhost:8080 (client) -> localhost:5000 (server)으로 이뤄지는데

서버에 별도 CORS 설정이 안되어 있어서 CORS 이슈가 발생하는 것으로 보입니다

이 부분 의도된 부분인지 궁금하여 질문합니다

fetch API 사용 시 클라이언트에서 해결하기에는 이슈가 있습니다

mode: 'no-cors' 사용 -> CORS 이슈 사라짐. 하지만 Content-Type: application/json 설정 불가능함 (??)

https://stackoverflow.com/a/37668444/12956829
https://stackoverflow.com/a/38163435/12956829
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#guard

### Solution

Flask-Cors 사용: https://flask-cors.readthedocs.io/en/latest/

requirements.txt 파일에 다음 추가
```
Flask-Cors==3.0.10
```

app.py 수정

```py
from flask_cors import CORS

...

CORS(app)
```

**Comment by leejaycoke** [comment]
고생하셨습니다.
감사합니다.  😋
